import Rating from "@mui/material/Rating";

export const products = [
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409234/tomato_gjfbpi.jpg",
      pname: "Tomato",
      price: 30,
      category: "Vegetables",
      rating: 4.0,
      qty: 1,
      reviews:[],
      description:"- Hybrid organic &",
      des2:"fresh (Loose), 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409229/moongdal_kvi8ce.webp",
      pname: "Moong Dal",
      price: 60,
      category: "Staples",
      rating: 3.7,
      qty: 1,
      reviews:[],
      description:"- Hesalre healthy",
      des2:"high fiber polished, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409229/onion_epuvvt.jpg",
      pname: "Onion",
      price: 60,
      category: "Vegetables",
      rating: 3.1,
      qty: 1,
      reviews:[],
      description:"/ Ullipaya - large",
      des2:"fresh and red, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409267/boost_qcbgdh.jpg",
      pname: "Boost",
      price: 489,
      category: "Snacks",
      rating: 3.3,
      qty: 1,
      reviews:[],
      description:"chocolate flavour NY",
      des2:" 2022 special edition, 500g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409234/toordal_kbwih9.jpg",
      pname: "Toor Dal",
      price: 125,
      category: "Staples",
      rating: 4.0,
      qty: 1,
      reviews:[],
      description:"/ Arhar Dal",
      des2:"unpolished, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409223/ghee_qlhjdg.jpg",
      pname: "Ghee",
      price: 504,
      category: "dairy & egg",
      rating: 3.6,
      qty: 1,
      reviews:[],
      description:"- pure vanaspathi ",
      des2:"cow ghee, 1L cans",
    },
    {
      img: "https://res.cloudinary.com/do4m8xtim/image/upload/v1670251417/apple_cjzjqz.jpg",
      pname: "Apple",
      price: 199,
      category: "Fruits",
      rating: 4,
      qty: 1,
      reviews:[],
      description:"- red and delicious,",
      des2:"unpolished ambri,500g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409225/madanglechips_jg3ct8.jpg",
      pname: "Mad Angles",
      price: 35,
      category: "Snacks",
      rating: 4.7,
      qty: 1,
      reviews:[],
      description:"- MMM",
      des2:"Masala Bingo, 40g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409226/maggi_vcnzwv.jpg",
      pname: "Maggi",
      price: 69,
      category: "packaged foods",
      rating: 4.3,
      qty: 1,
      reviews:[],
      description:"Magic Masala quick",
      des2:"on-the-go cup, 175g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409565/jimjam_zir7om.bmp",
      pname: "Jim Jam",
      price: 35,
      category: "Snacks",
      rating: 5.0,
      qty: 1,
      reviews:[],
      description:" - Cream Biscuit",
      des2:"crunchy & ready to eat",
    },
    {
      img: "https://res.cloudinary.com/do4m8xtim/image/upload/v1670251421/cheese_pplchf.jpg",
      pname: "Cheese",
      price: 130,
      category: "dairy & egg",
      rating: 4.5,
      qty: 1,
      reviews:[],
      description:"- processed protein",
      des2:"rich cubes, 5 Slices",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409233/saffolaoats_jukkwz.jpg",
      pname: "Saffola Oats",
      price: 130,
      category: "packaged foods",
      rating: 3.6,
      qty: 1,
      reviews:[],
      description:" - Breakfast",
      des2:"dietry cereal, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409220/carrot_reaeuz.jpg",
      pname: "Carrot",
      price: 45,
      category: "Vegetables",
      rating: 3.9,
      qty: 1,
      reviews:[],
      description:" - orange, fresh",
      des2:"ooty carrrots, 500g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409217/banana_usgvas.jpg",
      pname: "Fresho Banana",
      price: 48,
      category: "Fruits",
      rating: 4.1,
      qty: 1,
      reviews:[],
      description:" - red",
      des2:"fresh, half dozen",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409231/potato_qlipnz.png",
      pname: "Potato",
      price: 39,
      category: "Vegetables",
      rating: 3.0,
      qty: 1,
      reviews:[],
      description:"- starch rich",
      des2:"& fresh, 2kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409221/uraddal_xbvs7v.webp",
      pname: "Urad Dal",
      price: 131,
      category: "Staples",
      rating: 4.6,
      qty: 1,
      reviews:[],
      description:"MV royal Black",
      des2:"sabut, 250g each",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409224/ladyfinger_m2bgkm.jpg",
      pname: "Ladies' Finger",
      price: 32,
      category: "Vegetables",
      rating: 4.2,
      qty: 1,
      reviews:[],
      description:"/ Bendakaya",
      des2:"fresh boxed, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409226/milletflakes_zhyrkj.jpg",
      pname: "Millet Flakes",
      price: 118,
      category: "Staples",
      rating: 4.5,
      qty: 1,
      reviews:[],
      description:"- pearl millet",
      des2:"fibre & healthy, 400g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409244/pomegranate_xjagrf.jpg",
      pname: "Pomegranate",
      price: 168,
      category: "Fruits",
      rating: 3.4,
      qty: 1,
      reviews:[],
      description:"- unpeeled",
      des2:"red & fresh, 4 pcs",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409229/paneer_rcpd8v.jpg",
      pname: "Paneer",
      price: 92,
      category: "dairy & egg",
      rating: 4.7,
      qty: 1,
      reviews:[],
      description:"- Malai fresh",
      des2:"unsliced, 200g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409221/egg_v9bupj.jpg",
      pname: "Brown Egg",
      price: 36,
      category: "dairy & egg",
      rating: 4.4,
      qty: 1,
      reviews:[],
      description:"- free range",
      des2:"country egg, 3 pcs",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409230/orange_zpcot1.jpg",
      pname: "Orange",
      price: 107,
      category: "Fruits",
      rating: 3.6,
      qty: 1,
      reviews:[],
      description:"- imported Nagpur",
      des2:"Naranja/Santara, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409228/kurkure.jpeg_te1yvs.webp",
      pname: "Kurkure",
      price: 20,
      category: "Snacks",
      rating: 4.2,
      qty: 1,
      reviews:[],
      description:"- Masala Munch",
      des2:"Namkeen, 40g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409223/fortuneoil_njpknw.webp",
      pname: "Fortune Oil",
      price: 170,
      category: "Staples",
      rating: 4.7,
      qty: 1,
      reviews:[],
      description:"- expert pro ",
      des2:"immunity 1L pouch",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409231/pepsi_qoag7k.webp",
      pname: "Pepsi",
      price: 79,
      category: "Snacks",
      rating: 3.2,
      qty: 1,
      reviews:[],
      description:"- Carbonated 0% Sugar",
      des2:"blue Swag can, 250ml",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409224/kissanjam_h47wth.jpg",
      pname: "Fruit Jam",
      price: 67,
      category: "packaged foods",
      rating: 4.5,
      qty: 1,
      reviews:[],
      description:"- Happy Mixed",
      des2:"fruit jam, 425g box",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409223/horlicks_zrzvhx.jpg",
      pname: "Horlicks",
      price: 525,
      category: "Snacks",
      rating: 4.8,
      qty: 1,
      reviews:[],
      description:"- Health & nutrition",
      des2:"drink classic malt, 1kg",
    },
    {
      img: "https://res.cloudinary.com/do4m8xtim/image/upload/v1670251418/butter_vv2cx2.jpg",
      pname: "Butter",
      price: 248,
      category: "dairy & egg",
      rating: 3.7,
      qty: 1,
      reviews:[],
      description:"- Pasteurised sliced",
      des2:"chiplets, 100g (10 pcs)",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409233/strawberry_s1rlm3.jpg",
      pname: "Strawberry",
      price: 480,
      category: "Fruits",
      rating: 5.0,
      qty: 1,
      reviews:[],
      description:"- pulpy red",
      des2:"fresho, 200g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409234/turnip_vizo9e.jpg",
      pname: "Turnip",
      price: 64,
      category: "Vegetables",
      rating: 3.7,
      qty: 1,
      reviews:[],
      description:"- fresh purple",
      des2:"shalgam turnip, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409231/pasta_pn9kpc.jpg",
      pname: "Pasta",
      price: 159,
      category: "packaged foods",
      rating: 4.6,
      qty: 1,
      reviews:[],
      description:"- organic Nature",
      des2:"land Penne Pasta, 400g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409220/cauliflower_e66w2v.jpg",
      pname: "Cauliflower",
      price: 38,
      category: "Vegetables",
      rating: 4.1,
      qty: 1,
      reviews:[],
      description:"- fresh white",
      des2:"unwashed, 1 pc (approx.)",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409217/beetroot_xuxrxw.jpg",
      pname: "Beetroot",
      price: 88,
      category: "Vegetables",
      rating: 3.7,
      qty: 1,
      reviews:[],
      description:"- rooted whole",
      des2:"pink red, 2kg",
    },
 
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409218/wheat_xx1w1k.jpg",
      pname: "Whole Wheat",
      price: 220,
      category: "Staples",
      rating: 4.1,
      qty: 1,
      reviews:[],
      description:"- Super Soft",
      des2:"powdered Atta, 5kg pack",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409233/sorghum_ntb8l3.jpg",
      pname: "Sorghum",
      price: 80,
      category: "Staples",
      rating: 4.4,
      qty: 1,
      reviews:[],
      description:"- Jawar millet",
      des2:"organic polished, 1kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409217/basmati_gfedav.jpg",
      pname: "Basmati Rice",
      price: 825,
      category: "Staples",
      rating: 4.6,
      qty: 1,
      reviews:[],
      description:"- traditional ",
      des2:"and authentic, 5kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409222/grapes_uzg7kt.jpg",
      pname: "Grapes",
      price: 400,
      category: "Fruits",
      rating: 3.4,
      qty: 1,
      reviews:[],
      description:"- Bangalore blue",
      des2:"seedless residue free, 500g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409225/lays_z3olhk.jpg",
      pname: "Lays",
      price: 30,
      category: "Snacks",
      rating: 3.9,
      qty: 1,
      reviews:[],
      description:"- India's Magic Masala",
      des2:"flavor crunchy chips, 40g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409230/nice_euyoc0.jpg",
      pname: "Nice Biscuit",
      price: 45,
      category: "Snacks",
      rating: 3.1,
      qty: 1,
      reviews:[],
      description:"- Sugar sprinkled",
      des2:"coconut combo, 150g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409221/bread_qnxppe.jpg",
      pname: "Multigrain Bread",
      price: 132,
      category: "packaged foods",
      rating: 4.5,
      qty: 1,
      reviews:[],
      description:"",
      des2:"",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409216/7up_pgdtxn.jpg",
      pname: "7 Up",
      price: 30,
      category: "Snacks",
      rating: 4.2,
      qty: 1,
      reviews:[],
      description:"Swag can - sugarless",
      des2:"carbonated lime soda, 250ml",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409228/milk_xv5zfx.png",
      pname: "Bottled Milk",
      price: 52,
      category: "dairy & egg",
      rating: 4.8,
      qty: 1,
      reviews:[],
      description:"- UHT processed",
      des2:"homogenised & toned, 1L",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409231/pedigree_a0buki.jpg",
      pname: "Pedigree",
      price: 330,
      category: "packaged foods",
      rating: 4.0,
      qty: 1,
      reviews:[],
      description:"markies, for adult",
      des2:"dogs chicken & liver, 2kg",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409232/pumpkin_rxzx8p.jpg",
      pname: "Pumpkin",
      price: 45,
      category: "Vegetables",
      rating: 3.4,
      qty: 1,
      reviews:[],
      description:"- full uncut",
      des2:"fresh & seedless, 500g",
    },
    {
      img: "https://res.cloudinary.com/dnq6fx1oj/image/upload/v1670409226/cake_q6fc4g.jpg",
      pname: "Plum Cake",
      price: 320,
      category: "packaged foods",
      rating: 4.9,
      qty: 1,
      reviews:[],
      description:"- Plum Surprise",
      des2:"choco cake, 680g box",
    },
  ];
export const filtersArray = [
    {
      title: "Category",
      options: [
        "All",
        "Fruits",
        "Vegetables",
        "Staples",
        "Snacks",
        "Packaged Foods",
        "Dairy & egg",
      ],
    },
    {
      title: "Rating",
      options: [
        <Rating name="small-size" value={5} size="small" readOnly />,
        <Rating name="small-size" value={4} size="small" readOnly />,
        <Rating name="small-size" value={3} size="small" readOnly />,
        <Rating name="small-size" value={2} size="small" readOnly />,
        <Rating name="small-size" value={1} size="small" readOnly />,
      ],
    },
  ];
  export const storeDetails = [
    {
      id: 1,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186191/images_yaihak.jpg",
      store_name: "Jenine Winks",
      street_name: "3955 Gulseth Avenue",
      place: "Betulia",
      postel_code: "686508",
      rating: 4,
      phone_no: "8337606821",
    },
    {
      id: 2,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186185/images_obt7br.jpg",
      store_name: "Georgia Jedrzey",
      street_name: "41696 High Crossing Road",
      place: "Bouzov",
      postel_code: "783 25",
      rating: 4,
      phone_no: "5181055610",
    },
    {
      id: 3,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186014/download_x1q2lq.jpg",
      store_name: "Goraud Rolstone",
      street_name: "4502 Northwestern Center",
      place: "Oslo",
      postel_code: "0188",
      rating: 4,
      phone_no: "4809612659",
    },
    {
      id: 4,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186160/download_shnw5o.jpg",
      store_name: "Tanney Hedylstone",
      street_name: "160 Anthes Circle",
      place: "Shuangkou",
      postel_code: "923748",
      rating: 4,
      phone_no: "7108899009",
    },
    {
      id: 5,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186168/images_fz4ilv.jpg",
      store_name: "Jonis Caccavari",
      street_name: "003 Kinsman Parkway",
      place: "Kilcullen",
      postel_code: "Y25",
      rating: 4,
      phone_no: "5495558842",
    },
    {
      id: 6,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186177/images_p5ou6w.jpg",
      store_name: "Jarrod Robertsson",
      street_name: "65890 Sunbrook Place",
      place: "Cumba",
      postel_code: "923748",
      rating: 4,
      phone_no: "1226895865",
    },
    {
      id: 7,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186002/download_qha5ev.jpg",
      store_name: "Phip Colebrook",
      street_name: "06482 Kings Center",
      place: "Niquero",
      postel_code: "923748",
      rating: 4,
      phone_no: "9202324740",
    },
    {
      id: 8,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186018/download_mz9lxt.jpg",
      store_name: "Arlyne Flintoft",
      street_name: "32057 Commercial Way",
      place: "Arcos",
      postel_code: "35588-000",
      rating: 4,
      phone_no: "8873150208",
    },
    {
      id: 9,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186010/download_rkkhzo.jpg",
      store_name: "001 Stores",
      street_name: "489 Dwight Point",
      place: "Saint-Amand-les-Eaux",
      postel_code: "59734 CEDEX",
      rating: 4,
      phone_no: "1962416588",
    },
    {
      id: 10,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186168/images_fz4ilv.jpg",
      store_name: "Amitie Westlake",
      street_name: "933 Saint Paul Junction",
      place: "Dulles",
      postel_code: "20189",
      rating: 4,
      phone_no: "5718302115",
    },
    {
      id: 11,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186177/images_p5ou6w.jpg",
      store_name: "Harriet Ormonde",
      street_name: "72731 Roth Plaza",
      place: "Abut",
      postel_code: "2720",
      rating: 4,
      phone_no: "4697844165",
    },
    {
      id: 12,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186028/download_fsvlow.jpg",
      store_name: "Dannye Sebire",
      street_name: "79 Mariners Cove Avenue",
      place: "Mbala",
      postel_code: "923748",
      rating: 4,
      phone_no: "1748321775",
    },
    {
      id: 13,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186160/download_shnw5o.jpg",
      store_name: "Hugues Maddy",
      street_name: "2 Kropf Street",
      place: "Likupang",
      postel_code: "923748",
      rating: 4,
      phone_no: "3798119750",
    },
    {
      id: 14,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186383/images_kul3mx.jpg",
      store_name: "Callida Cancott",
      street_name: "195 Village Pass",
      place: "Morteros",
      postel_code: "2421",
      rating: 4,
      phone_no: "1054176157",
    },
    {
      id: 15,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186401/images_ydeq7j.jpg",
      store_name: "Kleon Leifer",
      street_name: "15615 Northfield Lane",
      place: "Khe Tre",
      postel_code: "923748",
      rating: 4,
      phone_no: "8361487065",
    },
    {
      id: 16,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186014/download_x1q2lq.jpg",
      store_name: "Clementine Blease",
      street_name: "674 Lotheville Circle",
      place: "Míthymna",
      postel_code: "923748",
      rating: 4,
      phone_no: "7222492470",
    },
    {
      id: 17,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186002/download_qha5ev.jpg",
      store_name: "Evangelin Wrinch",
      street_name: "20381 Eagle Crest Way",
      place: "Dū Qal‘ah",
      postel_code: "923748",
      rating: 4,
      phone_no: "7971500958",
    },
    {
      id: 18,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186018/download_mz9lxt.jpg",
      store_name: "Madelle Lambkin",
      street_name: "7833 Cascade Road",
      place: "Hässleholm",
      postel_code: "281 32",
      rating: 4,
      phone_no: "4543745950",
    },
    {
      id: 19,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186160/download_shnw5o.jpg",
      store_name: "Joyous Kowal",
      street_name: "32845 Blackbird Crossing",
      place: "Horní Suchá",
      postel_code: "735 35",
      rating: 4,
      phone_no: "1032079668",
    },
    {
      id: 20,
      image: "https://res.cloudinary.com/do4m8xtim/image/upload/v1675186185/images_obt7br.jpg",
      store_name: "Alleyn Minghetti",
      street_name: "6795 Dakota Avenue",
      place: "Krolevets’",
      postel_code: "923748",
      rating: 3,
      phone_no: "1168309217",
    },
  ];
  